config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :categories
  resources :businesses, as: "biz" do
    resources :reviews
  end
  resources :reviews
  devise_for :users, controllers: {  omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/:id' => 'users#show', as: 'user'

  get '/businesses/:offer_discounts' => 'businesses#index', as: 'biz_specials'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/businesses/:bitcoin' => 'spendables#bitcoin' as:
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :businesses
  has_many :reviews, through: :businesses
  has_many :spendables
  has_many :cryptos, through: :spendables

  validates :city, presence: true, uniqueness: true, allow_blank: false
  validates :state, presence: true, uniqueness: true, allow_blank: false
  validates :country, presence: true, uniqueness: true, allow_blank: false

  def full_location
    city != "N/A" ? full_location ||= "#{city}, #{state}, #{country}" : city
  end

  def self.order_by_city
    order(city: "asc")
  end

  # In the future,
  # I want to be able to separate within the dropdown menu by country,
  # or show city and state progressively after country is selected.

  # I want to be able to use Google maps or some other gem to validate locations.
  # I don't want users to be able to create non-existent locations.
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :set_business, only: [:edit, :update, :show, :destroy]
  has_scope :offer_discounts, :type => :boolean

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    if @business.save
      redirect_to biz_path(@business)
    else
      render :new   # render allows errors to appear. redirect does not.
    end
  end

  def edit
  end

  def update
    # binding.pry
    if @business.update(business_params)
      # @business.crypto_ids=(business_params[:crypto_attributes][:ids])
      flash[:alert] = "Business was successfully updated."
      redirect_to biz_path(@business)
    else
      flash[:alert] = "Fix me!"
      render :edit
    end
  end

  def index
    @businesses = Business.order_by_name.where(nil) # creates an anonymous scope. What does that mean?
    @businesses = Business.offer_discounts(params[:offer_discounts]) if params[:offer_discounts].present?
  end

  def show
  end

  def destroy
    @business.destroy
    flash[:alert] = "Business was successfully destroyed."
    redirect_to biz_index_path
  end

  private

  def set_business
    @business = Business.find_by(id: params[:id])
  end

  def business_params
    params.require(:business).permit(
      :name,
      :price_range,
      :description,
      :category_id,
      :location_id,
      :discount_offered,
      location_attributes: {},
      crypto_attributes: {}
    )
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper

  def display_links(current_user)
    # if current_user
    #   link_to "Delete Business", biz_path(@business), :method => :delete, :confirm => "Are you sure?" |
    #   link_to "Edit Information", edit_biz_path(@business) |
    #   link_to "Add Review for #{@business.name}", new_biz_review_path(@business, @review)
    # end
  end
end

app/views/businesses/_form.html.erb
<%= render 'layouts/errors', :variable => business %>

<%= form_for business, :url => url do |f| %>
  <label>Select category: </label>
  <%= f.collection_select :category_id, Category.order_by_name, :id, :name, include_blank: true %><br /><br />
  <label>Where is this business located?</label>
  <%= f.collection_select :location_id, Location.order_by_city, :id, :full_location, include_blank: true %><br />
  <label>Or enter new location here: </label><br />
    <%= f.fields_for :location_attributes do |location| %>
      <%= location.text_field :city, :placeholder => "City" %>
      <%= location.text_field :state, :placeholder => "State/Province" %>
      <%= location.text_field :country, :placeholder => "Country" %>
    <% end %><br /><br />

  <%= f.text_field :name, :placeholder => "Name of business..." %>
  <%= f.text_field :price_range, :size => "28", :placeholder => "Price range e.g. $, $$, $$$..." %><br /><br />
  <%= f.text_area :description, :size => "48x5", :placeholder => "Description..."%><br />

  <%= f.label "Check cryptocurrencies accepted: " %><br />
  <%= f.fields_for :crypto_attributes do |crypto| %>
    <%= crypto.collection_check_boxes :ids, Crypto.all, :id, :name, { checked: business.crypto_ids },
    { item_wrapper_class: 'checkbox_container'} %>
  <% end %><br /><br />

  <%= f.check_box :discount_offered, :checked => false %>
  <%= f.label "Discounts/specials offered for crypto payments?" %><br />

  <%= f.submit %>
<% end %>

app/views/businesses/edit.html.erb
<div class="">
  <% if !!flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>
</div>

<h1>Edit Business:</h1>

<%= render 'form', :business => @business, :url => biz_path(@business)%>

app/views/businesses/index.html.erb
<% if params[:offer_discounts] %>
  <h1>We offer discounts for crypto payments!</h1>
<% else %>
  <h1>List of All Businesses</h1>
<% end %>

<div class="">
  <ul>
    <% @businesses.each do |b| %>
      <li><%= link_to "#{b.name}", biz_path(b) %></li>
    <% end %>
  </ul>
</div>

app/views/businesses/new.html.erb
<div class="">
  <% if !!flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>
</div>

<h1>New Business: </h1>

<%= render 'form', :business => @business, :url => biz_index_path %>

app/views/businesses/show.html.erb
<div class="">
  <% if !!flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>
</div>

<h1><%= @business.name %></h1>
<h2><%= link_to "[Leave a review]", new_biz_review_path(@business, @review) %></h2>

<div class="">
  <label>Price Range: </label>
  <%= @business.price_range %><br />
  <label>Description: </label>
  <%= @business.description %><br />
  <label>Location: </label>
  <%= @business.location.full_location %><br />
  <label>Cryptocurrencies accepted: </label><br />
  <ul>
    <% @business.cryptos.each do |c| %>
      <li><%= c.name %></li>
    <% end %>
  </ul>
  <label>Discounts/specials offered for crypto payments? </label>
  <%= "#{@business.discount_offered}".capitalize %>
</div><br />

<div class="">
  <%= link_to "Delete Business", biz_path(@business), :method => :delete, :confirm => "Are you sure?" %> |
  <%= link_to "Edit Information", edit_biz_path(@business) %> |
  <%= link_to "View #{@business.name}'s Reviews", biz_reviews_path(@business) %>
</div><br />

<div class="">
  <%= link_to("Previous Page", biz_path(@business.previous_page)) if @business.previous_page %> |
  <%= link_to("Next Page", biz_path(@business.next_page)) if @business.next_page %>
</div>