config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :categories
  resources :businesses, as: "biz" do
    resources :reviews
  end
  resources :reviews
  devise_for :users, controllers: {  omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/:id' => 'users#show', as: 'user'

  get '/businesses/:offer_discounts' => 'businesses#index', as: 'biz_specials'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/businesses/:bitcoin' => 'spendables#bitcoin' as:
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :businesses

  # I want to create a module for self.order_by_name class methods because it's used in Category and Business models
  # Make the code DRY.
  
  def self.order_by_name
    order(name: "asc")
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login, except: [:show, :index]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
    @businesses = Business.where(category_id: @category.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<%= stylesheet_link_tag "categories" %>

<h1>Categories Index</h1>

<div class="category">
  <% @categories.each do |c| %>
    <li class="category"><%= link_to "#{c.name}", category_path(c) %></li>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= "#{@category.name}" %></h1>

<div>
  <ul>
    <% @businesses.each do |b| %>
      <li><%= link_to "#{b.name}", biz_path(b) %></li>
    <% end %>
  </ul>
</div>