config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :categories
  resources :businesses, as: "biz" do
    resources :reviews
  end
  resources :reviews
  devise_for :users, controllers: {  omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/:id' => 'users#show', as: 'user'

  get '/businesses/:offer_discounts' => 'businesses#index', as: 'biz_specials'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/businesses/:bitcoin' => 'spendables#bitcoin' as:
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :businesses
  has_many :reviews, through: :businesses
  has_many :spendables
  has_many :cryptos, through: :spendables

  validates :city, presence: true, uniqueness: true, allow_blank: false
  validates :state, presence: true, uniqueness: true, allow_blank: false
  validates :country, presence: true, uniqueness: true, allow_blank: false

  def full_location
    city != "N/A" ? full_location ||= "#{city}, #{state}, #{country}" : city
  end

  def self.order_by_city
    order(city: "asc")
  end

  # In the future,
  # I want to be able to separate within the dropdown menu by country,
  # or show city and state progressively after country is selected.

  # I want to be able to use Google maps or some other gem to validate locations.
  # I don't want users to be able to create non-existent locations.
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :set_business, except: [:create]
  before_action :set_review, only: [:edit, :show, :destroy]

  def new
    @review = Review.new
  end

  def create
    # Why must an instance variable be used here?
    @review = Review.new(review_params)
    if @review.save
      flash[:notice] = "Thank you for submitting a review!"
      redirect_to biz_review_path(@review.business, @review)
    else
      render :new
    end
  end

  def edit
  end

  def update
    # Why do I need to set @review manually here? My before_action doesn't work
    # It will create a new review instead.
    @review = Review.find_by(id: params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review was successfully updated."
      redirect_to biz_review_path(@business, @review)
    else
      flash[:alert] = "Fix me!"
      render :edit
    end
  end

  def show
  end

  def index
    @reviews = Review.all if !params[:biz_id]
  end

  def destroy
    @review.destroy
    flash[:alert] = "Review was successfully destroyed."
    redirect_to biz_reviews_path
  end

  private

  def set_business
    @business = Business.find_by(id: params[:biz_id])
  end

  def set_review
    @review = Review.find_by(id: params[:id])
  end

  def review_params
    params.require(:review).permit(
      :title,
      :comment,
      :rating,
      :would_recommend,
      :crypto_id,
      :user_id,
      :business_id,
      businesses_attributes: [
        :name,
        :price_range,
        :description,
        :category_id,
        :location_id,
        :discount_offered,
        crypto_ids: [],
        location_attributes: [
          :city,
          :state,
          :country
        ]
      ]
    )
  end
  # What's the difference between review_params and review_params(*args)? Why use one over the other?
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def display_rating(review)
    "#{review.rating} stars."
  end

  def display_email(review)
    review.user.email
  end

  def display_edit_link(review)
    link_to "Edit Review", edit_biz_review_path(@business, @review) if is_creator_of(review)
  end

  def display_delete_link(review)
    link_to "Delete", biz_review_path(@business, @review), :method => :delete, :confirm => "Are you sure?" if is_creator_of(review)
  end

  def display_all_link(review)
    link_to "See all #{@business.name}'s reviews", biz_reviews_path(@business)
  end

  def display_recommendation(review)
    if review.would_recommend
      "#{display_email(review)} recommends this business. #{display_rating(review)}"
    else
      "#{display_email(review)} does not recommend this business."
    end
  end

  private

  def is_creator_of(review)
    review.user == current_user
  end
end

app/views/reviews/_all.html.erb
<h1>All Reviews</h1>

<div class="">
  <ul>
    <% @reviews.each do |r| %>
      <li>
        <h2><%= link_to "#{r.business.name}", biz_path(r.business)%></h2>
        <h4><%= link_to "#{r.title}", biz_review_path(r.business, r) %></h4>
        <%= r.comment %>
        <% if r.would_recommend %>
          <p><%= "#{display_email r} recommends this business. #{display_rating r}" %></p>
        <% else %>
          <p><%= r.user.email %> does not recommend this business.</p>
        <% end %>
        <label>User paid in</label>
        <%= r.crypto.name %><br />
      </li>
    <% end %>
  </ul>
</div>

app/views/reviews/_form.html.erb
<%= render 'layouts/errors', :variable => review %>

<div>
  <%= form_for review, :url => url do |f| %>
    <% if !params[:biz_id] %>
      <div>
        <label>Which business are you reviewing?</label>
        <%= f.collection_select :business_id, Business.order_by_name, :id, :name, include_blank: true %><br /><br />
        <label>Or enter new business here: </label><br />
          <% # Have to make nested form %>
          <%= f.fields_for :businesses_attributes do |business| %>
            <%= label :category_id, "Select category: " %>
            <%= business.collection_select :category_id, Category.order_by_name, :id, :name, include_blank: true %><br />
            <%= business.text_field :name, :size => "50", :placeholder => "Enter name of business here..." %><br />
            <%= business.text_field :price_range, :size => "50", :placeholder => "Price range e.g. $, $$, $$$..." %><br />
            <%= business.text_area :description, :size => "48x5", :placeholder => "Description of goods and services..." %><br />
            <label>Select location: </label>
            <%= business.collection_select :location_id, Location.order_by_city, :id, :full_location,  include_blank: true %><br />
            <label>Or enter new location here: </label><br />
              <%= business.fields_for :location_attributes do |location| %>
                <%= location.text_field :city, :placeholder => "City" %>
                <%= location.text_field :state, :placeholder => "State/Province" %>
                <%= location.text_field :country, :placeholder => "Country" %>
              <% end %><br /><br />
            <%= business.check_box :discount_offered, :checked => false %>
            <%= label :discount_offered, "Discount offered for crypto payments?" %><br /><br />
            <%= label :crypto_ids, "Check all that apply:" %><br />
            <%= business.collection_check_boxes :crypto_ids, Crypto.all, :id, :name,
            { item_wrapper_class: 'checkbox_container'} %>
          <% end %>
      </div><br />
    <% end %>
    <div>
      <%= f.text_field :title, :placeholder => "Your review title here...", :size => "50x" %><br /><br />
    </div>
    <div>
      <%= f.text_area :comment, :placeholder => "How was your experience?", :size => "48x18" %><br />
    </div>
    <div>
      <label>How would you rate your experience? </label>
      <%= f.collection_radio_buttons :rating, [[5], [4], [3], [2], [1]], :first, :last %>
    </div>
    <div>
      <label>Which cryptocurrency did you pay in?</label>
      <%= f.collection_select :crypto_id, Crypto.all, :id, :name, include_blank: true %><br />
    </div>
    <div>
      <%= f.check_box :would_recommend, :checked => true %>
      <%= label :would_recommend, "Check, if you'd recommend this place to a friend." %>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <% if params[:biz_id] %>
      <%= f.hidden_field :business_id, :value => Business.find_by(id: params[:biz_id]).id %>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Edit your review: </h1>

<%= render 'form', :review => @review, :url => biz_review_path(@business, @review) %>

app/views/reviews/index.html.erb
<% if !!@business %>
  <h1><%= @business.name %>'s Reviews</h1>
  <h2><%= link_to "[Leave a review]", new_biz_review_path(@business, @review) %></h2>

  <div class="">
    <ul>
      <% @business.reviews.each do |r| %>
        <li>
          <h4><%= link_to "#{r.title}", biz_review_path(@business, r) %></h4>
          <%= r.comment %><br />
          <%= display_recommendation r %><br />
          <label>User paid in</label>
          <%= r.crypto.name %>.<br />
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <%= render 'all' %>
<% end %>

app/views/reviews/new.html.erb
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% end %>

<h1>Add a Review: </h1>

<%= render 'form', :review => @review, :url => reviews_path %>

app/views/reviews/show.html.erb
<h2><%= @review.title %></h2>

<div>
  <%= @review.comment %><br /><br />
  <%= display_rating @review %><br />

  <% # DRY code. Separate if statement below into helper? %>
  <% if @review.would_recommend %>
    <p><%= "#{display_email @review} recommends this business." %></p>
  <% else %>
    <p><%= @review.user.email %> does not recommend this business.</p>
  <% end %>

  <p>User paid in <%= @review.crypto.name %>.</p>
</div><br />

<%= display_edit_link @review %> |
<%= display_delete_link @review %> |
<%= display_all_link @review %>