config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  resources :categories
  resources :businesses, as: "biz" do
    resources :reviews
  end
  resources :reviews
  devise_for :users, controllers: {  omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/:id' => 'users#show', as: 'user'

  get '/businesses/:offer_discounts' => 'businesses#index', as: 'biz_specials'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/businesses/:bitcoin' => 'spendables#bitcoin' as:
end

app/views/layouts/_errors.html.erb
<% if variable.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(variable.errors.count, "error") %> prohibited this post from being saved
    </h2>

    <ul>
      <% variable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if !!flash[:message]%>
  <%= flash[:message] %>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav role="navigation">
    <ul id="menu-horizontal">
      <li><%= link_to "Biz Index", biz_index_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
      <% if !current_user %>
        <li class ="user-links"><%= link_to "Sign In", new_user_session_path %></li>
      <% else %>
        <li class="user-links"><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></li>
        <li class="user-links"><%= link_to "#{current_user.email}", edit_user_registration_path %></li>
        <li><%= link_to "My Reviews", user_path(current_user) %></li>
        <li><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>
      <% end %>
    </ul>
    <div id="menuToggle">
      <ul>
        <li><%= link_to "New Biz", new_biz_path %></li>
        <li><%= link_to "Add Review", new_review_path %></li>
        <li><%= link_to "Discounts/Specials", biz_index_path(:offer_discounts => 'true') %></li>
        <li><%= link_to "All Reviews", reviews_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpendItHere</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navbar' %>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
  
  <body>

    <%= yield %>
  </body>
</html>